### ISSUE TITLE
Random builder

### ISSUE THREAD

**Issue by ESSimon** [willryan/factory.ts#10]
This might be a bit meta, but is it possible to get a Factory instance that's going to produce random (but correctly typed) objects ?

I'd like to:
`Factory.makeFactory<Foo>().build()` and get a completely random Foo

This library does exactly this in Java: https://github.com/benas/random-beans

**Comment by ganqqwerty** [comment]
that would be a killer feature actually, no mocking libs have that

**Comment by adrianhara** [comment]
+1 I actually thought this would be supported but upon trying it found out it isn't.

**Comment by willryan** [comment]
Sorry for the long lag on replying to this, but I don't think that's possible with Typescript.  At least, not if `Foo` might be an `interface` or a `type`.  You can't write a function which takes a generic type and then iterates over its keys.

Basically for factory.ts the type inference is used to make it easy to specify your factory builder, but you still need to specify it.  You could use random generators for each property, e.g.

**Comment by willryan** [comment]
as per comment above, I don't think you can really build this in TS.  But you can specify factories that return random data.

**Comment by willryan** [comment]
as per comment above, I don't think you can really build this in TS.  But you can specify factories that return random data.
