### ISSUE TITLE
Placement of this.seqNum incrementation

### ISSUE THREAD

**Issue by quinnlangille** [willryan/factory.ts#11]
Hi! Just wondering if there was any reason why `this.seqNum++;` is placed before the first loop iteration in `Factory.build()`. 

As is, it's making the loop start at 1 vs 0, and ignoring the first index of test data. This makes it so our mock data needs to include a `null` first index, like this:

```
const currencyData: string[] = [null,  'USE', 'USE'];
const nameData: string[] = [null,  'Afghanistan', 'Albania'];
const priceDisplayRuleData: string[] = [null,  'base_price', 'base_price'];
```

I've opened a PR with the proposed implementation to address this (#12), let me know what you think!

**Comment by willryan** [comment]
Fixed by #17 (and subsequent commits for async version).
