### ISSUE TITLE
Use value from another field

### ISSUE THREAD

**Issue by coler-j** [willryan/factory.ts#41]
Is it possible to use a field value, from another fields's value?

I.e. 

```
export const someFactory = Factory.Sync.makeFactory<ISomeType>({
  id: uuidv4(),
  detailLink: Factory.each(i => `/${this.id}`)
})
```

**Comment by coler-j** [comment]
It seems like the `README` language is trying to imply there is a functional way to do this:

> Finally, you could instantiate a Derived<TOwner,TProperty> for the value of a property inside a Factory.makeFactory definition, but the type inference can't help you as much - you'll have to indicate the type of TOwner and TProperty.

**Comment by coler-j** [comment]
Kind of an ugly interface, but I was able to do this via:

```
const _someFactory = Factory.Sync.makeFactory<ISomeType>({
  id: uuidv4(),
  detailLink: Factory.each(i => `/${this.id}`)
})

export const someFactory = _someFactory.withDerivation1(['id'], 'detailLink', id =>
 `/${id}`
)
```

I think it would make more sense if there was an interface like:

```
const someFactory = Factory.Sync.makeFactory<ISomeType>({
  id: uuidv4(),
  detailLink: Factory.relatedVal(item => `/${item.id}`) // Get access to values of current item
})
```

**Comment by willryan** [comment]
Two years late, but I'm finally going through the backlog of issues a bit.

I do like the API you propose, but I'm not sure how to solve the ordering issues introduced. Say for example you defined `id` based on `item.detailLink`, as well as `detailLink` from `item.id`.  That would be invalid and unresolvable. If we make the user specify an ordering, you end up with a complicated graph to specify, and awkward type help (if possible at all). I think it makes more sense to just derive based off of initial instances, but you can do it a little more succinctly than your example:
```typescript
export const someFactory = Factory.Sync.makeFactory<ISomeType>({
  id: uuidv4(), // I'm assuming this returns a Generator and specifying the same uuid for all
  detailLink: 'TBD' // never used
}).withDerivation('detailLink', item => `/${item}`);
```
Of you could declare `detailLink` like:
```typescript
  detailLink: Sync.each(() => { throw "never reached" }),
```
to really drive the point home.

I'd also be fine with introducing `Sync.derivedLater()`  as a choice alongside `Sync.each()` and `Sync.val()`, which throws if you don't override it.

**Comment by nidomiro** [comment]
Unfortunately the approach with *Derivation introduces some bad sideeffects:
```ts
interface A {
  prop1: string;
  prop2: string;
  prop3: string;
}

interface B {
  a: A;
  b: string;
}

const factory2 = Factory.Sync.makeFactory<B>(() => {
  const value = "value";
  return {
    a: {} as A,
    b: value,
  };
}).withDerivation("a", (b) => ({
  prop1: b.b,
  prop2: b.b,
  prop3: b.b,
}));

console.log(inspect(factory2.build({ b: "b" }), false, 10, true));
// Correctly prints: `{ a: { prop1: 'b', prop2: 'b', prop3: 'b' }, b: 'b' }`

console.log(
  inspect(factory2.build({ b: "b", a: { prop1: "a" } }), false, 10, true)
);
// Incorrectly prints: `{ a: { func: [Function (anonymous)], prop1: 'a' }, b: 'b' }`
```

**Comment by nidomiro** [comment]
Further investigation shows that the `func`-property is the derivation function:

```ts
const deriveFunc = <T extends { b: string }>(b: T) => ({
  prop1: b.b,
  prop2: b.b,
  prop3: b.b,
});

const factory2 = Factory.Sync.makeFactory<B>(() => {
  const value = "value";
  return {
    a: {} as A,
    b: value,
  };
}).withDerivation("a", deriveFunc);

console.log(
  inspect(
    {
      "faultyResult.a": faultyResult.a,
      //@ts-expect-error
      "faultyResult.a.func": faultyResult.a.func,
      //@ts-expect-error
      "faultyResult.a.func.toString": faultyResult.a.func.toString(),
      //@ts-expect-error
      "faultyResult.a.func === deriveFunc": faultyResult.a.func === deriveFunc,
    },
    false,
    10,
    true
  )
);
```
prints:
```ts
{
  'faultyResult.a': { func: [Function: deriveFunc], prop1: 'a' },
  'faultyResult.a.func': [Function: deriveFunc],
  'faultyResult.a.func.toString': '(b) => ({\n    prop1: b.b,\n    prop2: b.b,\n    prop3: b.b,\n})',
  'faultyResult.a.func === deriveFunc': true
}
```

**Comment by willryan** [comment]
@nidomiro I'm ridiculously late on this, but I believe I have fixed your issue in v1.4.2. Please feel free to re-open if not.

**Comment by nidomiro** [comment]
seems to work so far, thanks :)

**Comment by jvdl** [comment]
@willryan as a sort-of continuation of this, I just noticed that having a `Factory.each` generator in the derivation logs out the generator for me. e.g.

```
export const thingFactory = Factory.Sync.makeFactory<Thing>({
  id: Factory.each(() => makeUuid()),
}).withDerivation("properties", (thing) => {
  return {
    id: thing.id,
    someOtherId: Factory.each(() => faker.string.uuid()),
  };
});
```

will cause `thingFactory.build()` to log:

```
{
  id: 'ca7a2125-0c47-4c2f-8426-645cb4cfb226',
  properties: {
    id: 'ca7a2125-0c47-4c2f-8426-645cb4cfb226',
    someOtherId: Generator {
      func: λ {...}
    }
  }
}
```

In my case it was easy enough to replace the factory with `faker.string.uuid()` but I could imagine that other cases may be less straightforward.
