### ISSUE TITLE
Node version bump causes install to fail

### ISSUE THREAD

**Issue by laurenbarker** [willryan/factory.ts#51]
Hello! I just wanted to give you a heads up that anyone running an older version of node may run into install failures with the latest version of `factory.ts` (v0.5.2). Anyone who uses `yarn` without `--ignore-engines` or `npm` with `engine-strict` set to true, won't be able to install the latest unless they are running node v14 or later.

Node v12 is still pretty common, so I imagine others will run into this.

**Comment by jrab** [comment]
just bumping this up -- our org noticed this same problem -- this change was a breaking change and the package json should have been bumped to a "major" version and not just a "patch" version increase. We've had to force our app to only load in the 0.5.1 version until we are able to update our build agents to a later node version.

**Comment by willryan** [comment]
Sorry about the original miss. Node 12 went EOL on 2022-04-30, so I'm closing this
