### ISSUE TITLE
An import path cannot end with a '.ts' extension

### ISSUE THREAD

**Issue by ucorina** [willryan/factory.ts#8]
Hey! First of all, thanks for a great library :)

I was just working on getting this set up in my project, and I get an error when I try to import the library in a typescript file:
`import * as Factory from 'factory.ts';`

The compiler says:
` error TS2691: An import path cannot end with a '.ts' extension. Consider importing 'factory' instead.`

I am using Typescript 2.4.2 and library version 0.2.2.

Is there something I am missing in the tsconfig? How can I get past this error?
Thanks!

**Comment by willryan** [comment]
I think maybe Typescript changed its compilation requirements since I wrote factory.ts.  Probably I just need to change how you import the library (e.g. 'factory-ts' or something).  I will take a look at this issue shortly (hopefully this week sometime?), but if you have time sooner than that I will happily merge a PR.  Thanks for the positive feedback, and sorry you are having an issue.

**Comment by willryan** [comment]
Hi again.  I tried to reproduce your issue without success.  Can you share your tsconfig.json? Or even better, can you provide a sample repo that has the problem?  Also, are you seeing the compile error via 'tsc' directly, or via your editor?  Thanks.

**Comment by ucorina** [comment]
I managed to track down the issue to one of the settings in my `tsconfig.json` file. Turns out I am using `moduleResolution: classic` instead of `node` and that is the root cause of the issue.

I made a repo with a simple file that fails to compile when running `tsc -p tsconfig.json`:
https://github.com/ucorina/factory-ts-error.

Reading the Typescript docs, they say:
> There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. If not specified, the default is Classic for --module AMD | System | ES2015 or Node otherwise.
> https://www.typescriptlang.org/docs/handbook/module-resolution.html

I am currently outputing AMD modules and this why the moduleResolution is set to `classic`. I tried changing it to `node` but then other parts of my code fail.

Since the docs also say that the classic "strategy is mainly present for backward compatibility" I understand if you choose to not support this use case :)

Thank you for your help so far and sorry for the late reply!

**Comment by rudyjahchan** [comment]
I actually have the same problem with `moduleResolution`: `node`. It only happens in the editor (Visual Studio Code).

My ts-config.json:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "lib": ["es2016", "dom"],
    "target": "es5",
    "jsx": "react",
    "sourceMap": true,
    "moduleResolution": "node",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitThis": true,
    "baseUrl": "./src",
    "paths": {
      "*": ["*"]
    }
  },
  "include": ["./src/**/*"],
  "exclude": ["./src/**/__tests__/**/*.js"]
}
```

I will see if I can whip up a repo with the same issue.

**Comment by rudyjahchan** [comment]
__UPDATE__: Scratch what I said. Turns out it was merely a Docker issue.

**Comment by seanders** [comment]
Just to add a data point, I'm using the `moduleResolution: node` option, and I'm still seeing this issue.

**Comment by fatcatt** [comment]
> I managed to track down the issue to one of the settings in my `tsconfig.json` file. Turns out I am using `moduleResolution: classic` instead of `node` and that is the root cause of the issue.
> 
> I made a repo with a simple file that fails to compile when running `tsc -p tsconfig.json`:
> https://github.com/ucorina/factory-ts-error.
> 
> Reading the Typescript docs, they say:
> 
> > There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. If not specified, the default is Classic for --module AMD | System | ES2015 or Node otherwise.
> > https://www.typescriptlang.org/docs/handbook/module-resolution.html
> 
> I am currently outputing AMD modules and this why the moduleResolution is set to `classic`. I tried changing it to `node` but then other parts of my code fail.
> 
> Since the docs also say that the classic "strategy is mainly present for backward compatibility" I understand if you choose to not support this use case :)
> 
> Thank you for your help so far and sorry for the late reply!


I am trying to use `moduleResolution: classic` instead of `node`;but  when i run "react-scripts start" to start my project,  the property named "moduleResolution" turn its value to "node" by himself!! sad

**Comment by MoSattler** [comment]
I have this very problem in CRA with typescript when running jest. 
```bash
tsc --noEmit -p tsconfig.json
```
fails!

config
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
```

**Comment by MoSattler** [comment]
The following solution works:
package.json
```json
  "devDependencies": {
    "factory.ts": "0.5.1",
    "factory": "file:node_modules/factory.ts"
  }
```

and then change the import to `factory`
```ts
import * as Factory from "factory";
```

**Comment by MoSattler** [comment]
A temporary solution is to create an alias
```json
  "devDependencies": {
    "factory.ts": "0.5.1",
    "factory": "file:node_modules/factory.ts"
  }
```
```ts
// import * as Factory from "factory.ts";
import * as Factory from "factory";
```

**Comment by MoSattler** [comment]
> A temporary solution is to create an alias
> 
> ```json
>   "devDependencies": {
>     "factory.ts": "0.5.1",
>     "factory": "file:node_modules/factory.ts"
>   }
> ```
> 
> ```ts
> // import * as Factory from "factory.ts";
> import * as Factory from "factory";
> ```

If this causes problems with `npm ci`, another option is to use
```json
"factory": "https://registry.npmjs.org/factory.ts/-/factory.ts-0.5.1.tgz"
```

**Comment by theaceofthespade** [comment]
This is a massive problem for anyone using parcel, which makes typescript otherwise painless...

**Comment by Stopa** [comment]
Having the same issue with `moduleResolution` set to `node`. Major annoyance

**Comment by bogdan-calapod** [comment]
I see that this is closed - any resolution on this ? Unfortunately @MoSattler's solution doesn't work for me :(

**Comment by MoSattler** [comment]
@bogdan-calapod I also had problems again. Since a solution to thus problem is not in sight, I ended up forking a similar library and maintain it myself. It's good a enough for my use case. https://github.com/mosattler/fabricator
